name: evievm_app

description: EVM

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  # --------------- CORE ---------------
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  dio: ^5.0.0
  dartz: ^0.10.1
  rxdart: ^0.28.0
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  injectable: ^2.4.2
  shared_preferences: ^2.0.13
  json_annotation: ^4.8.0
  easy_localization: ^3.0.1
  retrofit: ">=4.0.0 <5.0.0"
  file_picker: ^8.0.3
  
  # Notification
  signalr_netcore: ^1.3.4
  flutter_local_notifications: ^17.1.1
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0

  # Map
  panda_map:
    git: https://github.com/dttrung-99931/PandaMap.git
  here_panda_map:
    git: https://github.com/dttrung-99931/HerePandaMap.git

  # --------------- UI ---------------
  # cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  extended_image: ^9.1.0
  flutter_svg: ^2.0.10+1
  responsive_framework: ^1.4.0
  # rive: ^0.8.4
  flutter_screenutil: ^5.7.0
  another_flushbar: ^1.12.29
  package_info_plus: ^8.0.0
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  flutter_image_compress: ^2.3.0
  dio_cache_interceptor: ^3.5.0
  flutter_native_splash: 2.4.1
  # Skeleton loading
  redacted: ^1.0.13
  # Get backgorund color of images
  palette_generator: ^0.3.3
  # Crop, scale product image...
  image_cropper: ^9.1.0

  camerawesome: ^2.3.0
  # Fix compileSdkVersion is not specified error of geolocator_android
  geolocator_android: 4.6.1
  video_player: ^2.9.5

dependency_overrides:
  here_sdk:
    path: plugins/heresdk-explore-flutter # 4.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  retrofit_generator: ^8.1.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Light.ttf
            weight: 300
          - asset: assets/fonts/OpenSans-Regular.ttf
            weight: 400
          - asset: assets/fonts/OpenSans-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/OpenSans-Bold.ttf
            weight: 700
