name: evievm_app

description: EVM

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # --------------- CORE ---------------
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  dio: ^5.0.0
  dartz: ^0.10.1
  rxdart: ^0.27.5
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  injectable: ^2.4.2
  shared_preferences: ^2.0.13
  json_annotation: ^4.8.0
  easy_localization: ^3.0.1
  retrofit: ">=4.0.0 <5.0.0"
  http_parser: ^4.0.2
  socket_io_client: ^2.0.2
  camera: ^0.11.0
  mobile_scanner: ^5.1.1
  file_picker: ^8.0.3
  
  # Notification
  signalr_netcore: ^1.3.4
  flutter_local_notifications: ^17.1.1
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2

  # Map
  # panda_map:
  #   #
    # git: https://github.com/dttrung-99931/PandaMap.git
  here_panda_map:
    #

  # --------------- UI ---------------
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  extended_image: ^8.2.0
  flutter_svg: ^2.0.10+1
  responsive_framework: ^1.4.0
  # rive: ^0.8.4
  expandable: ^5.0.1
  syncfusion_flutter_datepicker:
    path: package/syncfusion_flutter_datepicker
  flutter_screenutil: ^5.7.0
  another_flushbar: ^1.12.29
  package_info_plus: ^8.0.0
  expandable_page_view: ^1.0.17 # Page view wrap height content    
  carousel_slider: ^4.2.1
  dotted_border: ^2.1.0
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  retrofit_generator: ^8.1.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/rives/
    - assets/translations/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 500
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial-Light.ttf
          weight: 300
        - asset: assets/fonts/Arial-Regular.ttf
          weight: 400
        - asset: assets/fonts/Arial-Bold.ttf
          weight: 700
